name: scrolloff
description: "A focus app that helps users stay productive by blocking distracting social media apps."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core UI and Animation
  simple_animations: ^5.0.2
  animations: ^2.0.11
  auto_size_text: ^3.0.0
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1
  fl_chart: ^0.66.2
  material_symbols_icons: ^4.2719.3
  
  # System Integration - using dynamic_color instead of system_theme
  dynamic_color: ^1.7.0
  device_info_plus: ^9.1.1
  app_settings: ^5.1.1
  flutter_local_notifications: ^16.3.2
  
  # Storage and Preferences
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  flutter_audio_capture: ^1.1.11
  
  # Authentication (for future Google Sign-In implementation)
  # google_sign_in: ^6.2.1
  
  # Utility
  intl: ^0.20.2  # Updated to resolve dependency conflict with device_preview
  timer_builder: ^2.0.0
  pausable_timer: ^3.1.0+3
  
  # State Management
  provider: ^6.1.1
  hugeicons: ^0.0.11
  audioplayers: ^5.2.1
  just_waveform: ^0.0.7

  # Networking
  http: ^1.1.0
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  device_preview: ^1.2.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: CustomBold
      fonts:
        - asset: assets/font/bold.ttf
          weight: 700

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

  assets:
    - assets/audio/eng.mp3
    - assets/audio/tam.mp3
    - assets/audio/hindi.mp3
    - assets/audio/french.mp3
    - assets/audio/eng.lrc
    - assets/audio/tam.lrc
    - assets/audio/hindi.lrc
    - assets/audio/french.lrc
    - assets/image/logo.png
